image:
  - Visual Studio 2022
  - Ubuntu2004

install:
  - node --version
  - npm install

build_script:
  - sh: npm run dist:linux
  - cmd: npm run dist:win

artifacts:
  - path: dist\*.exe
  - path: dist/*.AppImage
